version: "3.4"

services:

  api:
    build:
      context: api
      target: dev
    container_name: api-dev
    environment:
      API_PORT: 4242
    ports:
      - 4242:4242
    volumes:
      - "./api:/app"

  front:
    build:
      context: front
      target: dev
    container_name: front-dev
    environment:
      - API_HOST=''
      # enable
      # https://stackoverflow.com/questions/22111060/what-is-the-difference-between-expose-and-publish-in-docker
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./front:/app"
    ports:
      - 3000:3000
    # fix docker exiting on react hot reload
    # https://stackoverflow.com/questions/60790440/docker-container-exiting-immediately-after-starting-when-using-npm-init-react-ap
    stdin_open: true

  nginx:
    build:
      context: nginx
      target: dev
    container_name: nginx-dev
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - front
